name: Nx Publish

# Declare default permissions as read-only
permissions: read-all

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # needed for provenance data generation
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@v6
              with:
                  node-version-file: package.json
                  cache: "npm"
                  registry-url: "https://registry.npmjs.org/"

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v5

            - run: RELEASE_VERSION=$(npm pkg get version --workspaces | jq -r '.["@stricli/core"]')
            - run: npx nx release publish
              env:
                  NPM_CONFIG_PROVENANCE: true

            - run: gh release edit "v$RELEASE_VERSION" --prerelease=false --latest
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
