name: Nx Publish

# Declare default permissions as read-only
permissions: read-all

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            dry_run:
                type: boolean
                required: true
                default: true
                description: Add `--dry-run` flag to publish command

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # needed for provenance data generation
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@v6
              with:
                  node-version-file: package.json
                  cache: "npm"
                  registry-url: "https://registry.npmjs.org/"

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v5

            - run: npx nx release publish ${{ inputs.dry_run && '--dry-run' || '' }}
              env:
                  NPM_CONFIG_PROVENANCE: true
