name: Nx Publish

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                required: true
                default: true
                description: Trigger publish as a dry run, so no packages are published.

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # needed for provenance data generation
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  registry-url: "https://registry.npmjs.org/"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v4

            - run: npx nx release publish ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
