name: Nx Release

on:
    workflow_dispatch:
        inputs:
            dry-run:
                required: true
                type: boolean
                default: true
                description: This should be a dry run release where no changes are committed/applied.

permissions:
    actions: read
    contents: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - run: npm ci --legacy-peer-deps
            - uses: nrwl/nx-set-shas@v4

            - run: git config --global user.name "github-actions[bot]"
            - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            - run: cp scripts/dco_commit_msg_hook.sh .git/hooks/prepare-commit-msg

            - run: npx nx release --yes ${{ inputs.dry-run && '--dry-run' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
                  DCO_NAME: ${{ sender.name }}
                  DCO_EMAIL: ${{ sender.email }}
